logger:
  period: 1d
  count: 3
  path: log
auth:
  secret: thisisverysecure
  salt: d3nm4s3n0
  curves: secp256k1
  aesKey:
    iterations: 191
    hashBytes: 32
  aesSalt:
    iterations: 297
    hashBytes: 16
  loginExpiry: 120
  # singleSession: true
  # tokenExpiry: 1
  # sessionExpiry: 2
  singleSession: false
  tokenExpiry: 30
  sessionExpiry: 300
  pbkdf2:
    iterations: 573
    hashBytes: 64
  pbkdf2App:
    iterations: 7473
    hashBytes: 64
api:
  protocol: http
  host: localhost
  port: 5000
redis:
  host: localhost
  port: 5006
mongodb:
  host: localhost
  port: 5008
  user: admin
  password: dodol123

keys:
  auth:
    key: |
      -----BEGIN PUBLIC KEY-----
      MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEAckN6k0lflLvqIpEACUsNPubsVtHeom3
      YMT9ZrIGIITEukV/+S371KTgyD1KC22ucwznpsffJQtEIihJcj2h3g==
      -----END PUBLIC KEY-----
  account:
    key: |
      -----BEGIN PUBLIC KEY-----
      MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnpWaHslCxvRihdsihzEEGJrtZ5QVIVrk
      BZINy2fMMqB6P+hvjxa3Ptx8JJtqID6o8sMi7V6sBt2cg39onv1JNg==
      -----END PUBLIC KEY-----
  common:
    pkey: |
      -----BEGIN EC PRIVATE KEY-----
      MHQCAQEEIIBhedo5zOREbMyoYlo/kdIDs7YMOTZwmCPOH3MsvNQ4oAcGBSuBBAAK
      oUQDQgAE3ejh5u9NsM33x+gyId8wLOIAAsWCY7PKMnMgay181cbZlkf6rJr3ykXE
      YE7Ni3PS1CFCApLn5lwBmmESzhg1+Q==
      -----END EC PRIVATE KEY-----
