logger:
  period: 1d
  count: 3
  path: log
auth:
  secret: thisisverysecure
  salt: d3nm4s3n0
  curves: secp256k1
  aesKey:
    iterations: 191
    hashBytes: 32
  aesSalt:
    iterations: 297
    hashBytes: 16
  loginExpiry: 120
  # singleSession: true
  # tokenExpiry: 1
  # sessionExpiry: 2
  singleSession: false
  tokenExpiry: 30
  sessionExpiry: 300
  pbkdf2:
    iterations: 573
    hashBytes: 64
  pbkdf2App:
    iterations: 7473
    hashBytes: 64
api:
  protocol: http
  host: localhost
  port: 5000
redis:
  host: localhost
  port: 5006
mongodb:
  host: localhost
  port: 5008
  user: admin
  password: dodol123

keys:
  auth:
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEO5gl9qu1vfftugBe3j5fJetJUhbV
      4GFtYCuLVvpGX44dgjmjjKQ6fAAiYagdQlo5FAlh4Mp3ua6kFk2G15tywA==
      -----END PUBLIC KEY-----
    pkey: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIOTTmjPnVkVphJ/YGgBynBBuBdhPM1grwX3b+eFpS3fAoAoGCCqGSM49
      AwEHoUQDQgAEO5gl9qu1vfftugBe3j5fJetJUhbV4GFtYCuLVvpGX44dgjmjjKQ6
      fAAiYagdQlo5FAlh4Mp3ua6kFk2G15tywA==
      -----END EC PRIVATE KEY-----
  account:
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEP9Xj+RfjpBxjmURMLozwuD5BhG8y
      zdh7lwTUT0dkNLZuWbma+JLNBh8H/xVBx7Znu/aTKIICq10yNL0vHSVgEg==
      -----END PUBLIC KEY-----
    pkey: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEILMJRGTXYxO2w25MQ/VLFEvFP6e2yaeHMCx9EWNz5pTBoAoGCCqGSM49
      AwEHoUQDQgAEP9Xj+RfjpBxjmURMLozwuD5BhG8yzdh7lwTUT0dkNLZuWbma+JLN
      Bh8H/xVBx7Znu/aTKIICq10yNL0vHSVgEg==
      -----END EC PRIVATE KEY-----
